services:
    chat-server:
        build: ./chat-server
        ports:
            - "3000:3000"
        restart: always

    # DOESNT WORK
    frontend-viewer:
        build:
            context: ./frontend
            args:
                APP_NAME: viewer
        ports:
            - "4200:80"
        # depends_on:
        #     - chat-server
        restart: always
    # DOESNT WORK
    frontend-streamer:
        build:
            context: ./frontend
            args:
                APP_NAME: streamer
        ports:
            - "4300:80"
        # depends_on:
        #     - truYou-auth
        restart: always

    ingest-server:
        build: ./ingest-server
        ports:
            - "4000:4000" # Adjust depending on how ingest works
        restart: always
        volumes:
            - ./ingest-server/recordings:/app/recordings
        # depends_on:
        #     - streaming-server

    streaming-server:
        build: ./streaming-server
        ports:
            - "1935:1935" # RTMP ingest
            - "8080:80" # HLS stream
        volumes:
            - streaming-hls:/var/www/hls
            - streaming-recordings:/var/www/recordings
        restart: always

    streaming-api:
        build: ./streaming-api
        volumes:
            - streaming-hls:/app/hls # Mount the same HLS folder if needed
            - streaming-recordings:/app/recordings
        ports:
            - "5000:4000"
        depends_on:
            - streaming-server

    # truYou-auth:
    #     build: ./truYou-auth
    #     ports:
    #         - "5000:5000"
    #     restart: always
    #     environment:
    #         MONGO_URL: mongodb://mongo:27017/truyou

volumes:
    streaming-hls:
    streaming-recordings:
